CREATE DATABASE DENTALCARE;
USE DENTALCARE;

CREATE TABLE [AspNetRoles] (
    [Id] NVARCHAR(128) NOT NULL,
    [Name] NVARCHAR(256) NOT NULL,
    CONSTRAINT [PK_AspNetRoles] PRIMARY KEY ([Id])
);

CREATE TABLE [AspNetUsers] (
    [Id] NVARCHAR(128) NOT NULL,
    [Email] NVARCHAR(256) NULL,
    [EmailConfirmed] BIT NOT NULL,
    [PasswordHash] NVARCHAR(MAX) NULL,
    [SecurityStamp] NVARCHAR(MAX) NULL,
    [PhoneNumber] NVARCHAR(MAX) NULL,
    [PhoneNumberConfirmed] BIT NOT NULL,
    [TwoFactorEnabled] BIT NOT NULL,
    [LockoutEndDateUtc] DATETIME NULL,
    [LockoutEnabled] BIT NOT NULL,
    [AccessFailedCount] INT NOT NULL,
    [UserName] NVARCHAR(256) NOT NULL,
    CONSTRAINT [PK_AspNetUsers] PRIMARY KEY ([Id])
);

CREATE TABLE [AspNetUserClaims] (
    [Id] INT IDENTITY(1,1) NOT NULL,
    [UserId] NVARCHAR(128) NOT NULL,
    [ClaimType] NVARCHAR(MAX) NULL,
    [ClaimValue] NVARCHAR(MAX) NULL,
    CONSTRAINT [PK_AspNetUserClaims] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId] FOREIGN KEY ([UserId])
        REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
);

CREATE TABLE [AspNetUserLogins] (
    [LoginProvider] NVARCHAR(128) NOT NULL,
    [ProviderKey] NVARCHAR(128) NOT NULL,
    [UserId] NVARCHAR(128) NOT NULL,
    CONSTRAINT [PK_AspNetUserLogins] PRIMARY KEY ([LoginProvider], [ProviderKey], [UserId]),
    CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId] FOREIGN KEY ([UserId])
        REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
);

CREATE TABLE [AspNetUserRoles] (
    [UserId] NVARCHAR(128) NOT NULL,
    [RoleId] NVARCHAR(128) NOT NULL,
    CONSTRAINT [PK_AspNetUserRoles] PRIMARY KEY ([UserId], [RoleId]),
    CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId] FOREIGN KEY ([RoleId])
        REFERENCES [AspNetRoles] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId] FOREIGN KEY ([UserId])
        REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
);

CREATE TABLE FIDE_ESTADO_TB (
    ID_ESTADO INT NOT NULL,
    NOMBRE_ESTADO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY (ID_ESTADO)
);

CREATE TABLE FIDE_METODO_PAGO_TB (
    ID_METODO_PAGO INT NOT NULL,
    DESCRIPCION VARCHAR(100) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_METODO_PAGO PRIMARY KEY (ID_METODO_PAGO),
    CONSTRAINT METODO_PAGO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_ANTICIPO_TB (
    ID_ANTICIPO INT NOT NULL,
    ID_METODO_PAGO INT NOT NULL,
    FECHA DATE NULL,
    MONTO DECIMAL(10,2) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_ANTICIPO PRIMARY KEY (ID_ANTICIPO),
    CONSTRAINT ANTICIPO_METODO_PAGO_FK FOREIGN KEY (ID_METODO_PAGO)
        REFERENCES FIDE_METODO_PAGO_TB (ID_METODO_PAGO),
    CONSTRAINT ANTICIPO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_GASTO_TB (
    ID_GASTO INT NOT NULL,
    DESCRIPCION VARCHAR(200) NULL,
    MONTO DECIMAL(10,2) NULL,
    FECHA DATE NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_GASTO PRIMARY KEY (ID_GASTO),
    CONSTRAINT GASTO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_CONTABILIDAD_TB (
    ID_CONTABILIDAD INT NOT NULL,
    MONTO DECIMAL(10,2) NULL,
    ID_METODO_PAGO INT NOT NULL,
    ID_GASTO INT NOT NULL,
    ID_ANTICIPO INT NOT NULL,
    FECHA DATE NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_CONTABILIDAD PRIMARY KEY (ID_CONTABILIDAD),
    CONSTRAINT CONTABILIDAD_METODO_PAGO_FK FOREIGN KEY (ID_METODO_PAGO)
        REFERENCES FIDE_METODO_PAGO_TB (ID_METODO_PAGO),
    CONSTRAINT CONTABILIDAD_GASTO_FK FOREIGN KEY (ID_GASTO)
        REFERENCES FIDE_GASTO_TB (ID_GASTO),
    CONSTRAINT CONTABILIDAD_ANTICIPO_FK FOREIGN KEY (ID_ANTICIPO)
        REFERENCES FIDE_ANTICIPO_TB (ID_ANTICIPO),
    CONSTRAINT CONTABILIDAD_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_PROVINCIA_TB (
    ID_PROVINCIA INT NOT NULL,
    NOMBRE_PROVINCIA VARCHAR(100) NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_PROVINCIA PRIMARY KEY (ID_PROVINCIA),
    CONSTRAINT PROVINCIA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_CANTON_TB (
    ID_CANTON INT NOT NULL,
    NOMBRE_CANTON VARCHAR(100) NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_CANTON PRIMARY KEY (ID_CANTON),
    CONSTRAINT CANTON_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_DISTRITO_TB (
    ID_DISTRITO INT NOT NULL,
    NOMBRE_DISTRITO VARCHAR(100) NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_DISTRITO PRIMARY KEY (ID_DISTRITO),
    CONSTRAINT DISTRITO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_AREA_USUARIO_TB (
    ID_AREA_USUARIO INT NOT NULL,
    NOMBRE_TIPO_USUARIO VARCHAR(100) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_AREA_USUARIO PRIMARY KEY (ID_AREA_USUARIO),
    CONSTRAINT AREA_USUARIO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_ESPECIALIDAD_USUARIO_TB (
    ID_ESPECIALIDAD INT NOT NULL,
    NOMBRE_ESPECIALIDAD VARCHAR(100) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_ESPECIALIDAD_USUARIO PRIMARY KEY (ID_ESPECIALIDAD),
    CONSTRAINT ESPECIALIDAD_USUARIO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_USUARIO_TB (
    ID_USUARIO INT NOT NULL,
    ASPNET_USER_ID NVARCHAR(128) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMER_APELLIDO VARCHAR(100) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(100) NULL,
    ID_AREA_USUARIO INT NOT NULL,
    ID_ESPECIALIDAD INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    FECHA_CONTRATACION DATE NULL,
    FECHA_DE_CREACION DATETIME NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT USUARIO_ASPNET_FK FOREIGN KEY (ASPNET_USER_ID)
        REFERENCES [AspNetUsers] ([Id]),
    CONSTRAINT USUARIO_AREA_FK FOREIGN KEY (ID_AREA_USUARIO)
        REFERENCES FIDE_AREA_USUARIO_TB (ID_AREA_USUARIO),
    CONSTRAINT USUARIO_ESPECIALIDAD_FK FOREIGN KEY (ID_ESPECIALIDAD)
        REFERENCES FIDE_ESPECIALIDAD_USUARIO_TB (ID_ESPECIALIDAD),
    CONSTRAINT USUARIO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_CEDULA_TB (
    ID_USUARIO INT NOT NULL,
    TIPO_CEDULA VARCHAR(50) NULL,
    NUMERO_CEDULA VARCHAR(20) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT CEDULA_USUARIO_FK FOREIGN KEY (ID_USUARIO)
        REFERENCES FIDE_USUARIO_TB (ID_USUARIO),
    CONSTRAINT CEDULA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_TELEFONO_TB (
    ID_USUARIO INT NOT NULL,
    NUMERO_TELEFONO VARCHAR(20) NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT TELEFONO_USUARIO_FK FOREIGN KEY (ID_USUARIO)
        REFERENCES FIDE_USUARIO_TB (ID_USUARIO),
    CONSTRAINT TELEFONO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_CORREO_TB (
    ID_USUARIO INT NOT NULL,
    CORREO VARCHAR(150) NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT CORREO_USUARIO_FK FOREIGN KEY (ID_USUARIO)
        REFERENCES FIDE_USUARIO_TB (ID_USUARIO),
    CONSTRAINT CORREO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_DIRECCION_TB (
    ID_USUARIO INT NOT NULL,
    ID_PROVINCIA INT NOT NULL,
    ID_CANTON INT NOT NULL,
    ID_DISTRITO INT NOT NULL,
    OTRAS_SENAS VARCHAR(300) NULL,
    ID_ESTADO INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
    CONSTRAINT DIRECCION_USUARIO_FK FOREIGN KEY (ID_USUARIO)
        REFERENCES FIDE_USUARIO_TB (ID_USUARIO),
    CONSTRAINT DIRECCION_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA)
        REFERENCES FIDE_PROVINCIA_TB (ID_PROVINCIA),
    CONSTRAINT DIRECCION_CANTON_FK FOREIGN KEY (ID_CANTON)
        REFERENCES FIDE_CANTON_TB (ID_CANTON),
    CONSTRAINT DIRECCION_DISTRITO_FK FOREIGN KEY (ID_DISTRITO)
        REFERENCES FIDE_DISTRITO_TB (ID_DISTRITO),
    CONSTRAINT DIRECCION_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_MOTIVO_CANCELACION_TB (
    ID_CANCELACION INT NOT NULL,
    DESCRIPCION VARCHAR(300) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_MOTIVO_CANCELACION PRIMARY KEY (ID_CANCELACION),
    CONSTRAINT MOTIVO_CANCELACION_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_MOTIVO_CITA_TB (
    ID_MOTIVO INT NOT NULL,
    DESCRIPCION VARCHAR(300) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_MOTIVO_CITA PRIMARY KEY (ID_MOTIVO),
    CONSTRAINT MOTIVO_CITA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_CITAS_TB (
    ID_CITA INT NOT NULL,
    FECHA DATE NULL,
    ID_MOTIVO INT NOT NULL,
    ID_CANCELACION INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_CITAS PRIMARY KEY (ID_CITA),
    CONSTRAINT CITAS_MOTIVO_FK FOREIGN KEY (ID_MOTIVO)
        REFERENCES FIDE_MOTIVO_CITA_TB (ID_MOTIVO),
    CONSTRAINT CITAS_CANCELACION_FK FOREIGN KEY (ID_CANCELACION)
        REFERENCES FIDE_MOTIVO_CANCELACION_TB (ID_CANCELACION),
    CONSTRAINT CITAS_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_USUARIO_CITA_TB (
    ID_USUARIO INT NOT NULL,
    ID_CITA INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_CITA),
    CONSTRAINT USUARIO_CITA_USUARIO_FK FOREIGN KEY (ID_USUARIO)
        REFERENCES FIDE_USUARIO_TB (ID_USUARIO),
    CONSTRAINT USUARIO_CITA_CITA_FK FOREIGN KEY (ID_CITA)
        REFERENCES FIDE_CITAS_TB (ID_CITA)
);

CREATE TABLE FIDE_TRATAMIENTO_TB (
    ID_TRATAMIENTO INT NOT NULL,
    DESCRIPCION VARCHAR(300) NULL,
    FECHA_INICIO DATE NULL,
    FECHA_FIN DATE NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_TRATAMIENTO PRIMARY KEY (ID_TRATAMIENTO),
    CONSTRAINT TRATAMIENTO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_PROCEDIMIENTO_TB (
    ID_PROCEDIMIENTO INT NOT NULL,
    ID_CITA INT NOT NULL,
    ID_TRATAMIENTO INT NOT NULL,
    DESCRIPCION VARCHAR(300) NULL,
    FECHA DATE NULL,
    OBSERVACIONES VARCHAR(500) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_PROCEDIMIENTO PRIMARY KEY (ID_PROCEDIMIENTO),
    CONSTRAINT PROCEDIMIENTO_CITA_FK FOREIGN KEY (ID_CITA)
        REFERENCES FIDE_CITAS_TB (ID_CITA),
    CONSTRAINT PROCEDIMIENTO_TRAT_FK FOREIGN KEY (ID_TRATAMIENTO)
        REFERENCES FIDE_TRATAMIENTO_TB (ID_TRATAMIENTO),
    CONSTRAINT PROCEDIMIENTO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_PROCEDIMIENTO_CITA_TB (
    ID_PROCEDIMIENTO INT NOT NULL,
    ID_CITA INT NOT NULL,
    PRIMARY KEY (ID_PROCEDIMIENTO, ID_CITA),
    CONSTRAINT PROC_CITA_PROCEDIMIENTO_FK FOREIGN KEY (ID_PROCEDIMIENTO)
        REFERENCES FIDE_PROCEDIMIENTO_TB (ID_PROCEDIMIENTO),
    CONSTRAINT PROC_CITA_CITA_FK FOREIGN KEY (ID_CITA)
        REFERENCES FIDE_CITAS_TB (ID_CITA)
);

CREATE TABLE FIDE_NOTA_CLINICA_TB (
    ID_NOTA INT NOT NULL,
    DESCRIPCION VARCHAR(500) NULL,
    FECHA DATE NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_NOTA_CLINICA PRIMARY KEY (ID_NOTA),
    CONSTRAINT NOTA_CLINICA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_PIEZA_DENTAL_TB (
    ID_PIEZA INT NOT NULL,
    NUMERO_PIEZA VARCHAR(10) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_PIEZA_DENTAL PRIMARY KEY (ID_PIEZA),
    CONSTRAINT PIEZA_DENTAL_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_ODONTOGRAMA_TB (
    ID_ODONTOLOGIA INT NOT NULL,
    FECHA DATE NULL,
    ID_PIEZA INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_ODONTOGRAMA PRIMARY KEY (ID_ODONTOLOGIA),
    CONSTRAINT ODONTOGRAMA_PIEZA_FK FOREIGN KEY (ID_PIEZA)
        REFERENCES FIDE_PIEZA_DENTAL_TB (ID_PIEZA),
    CONSTRAINT ODONTOGRAMA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_ALERTA_MEDICA_TB (
    ID_ALERTA INT NOT NULL,
    DESCRIPCION VARCHAR(300) NULL,
    NIVEL_RIESGO VARCHAR(50) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_ALERTA_MEDICA PRIMARY KEY (ID_ALERTA),
    CONSTRAINT ALERTA_MEDICA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_CONSENTIMIENTO_TB (
    ID_CONSENTIMIENTO INT NOT NULL,
    DESCRIPCION VARCHAR(500) NULL,
    FECHA DATE NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_CONSENTIMIENTO PRIMARY KEY (ID_CONSENTIMIENTO),
    CONSTRAINT CONSENTIMIENTO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_TIPO_ARCHIVO_TB (
    ID_TIPO_ARCHIVO INT NOT NULL,
    NOMBRE_TIPO VARCHAR(100) NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_TIPO_ARCHIVO PRIMARY KEY (ID_TIPO_ARCHIVO),
    CONSTRAINT TIPO_ARCHIVO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_ARCHIVO_TB (
    ID_ARCHIVO INT NOT NULL,
    ID_TIPO_ARCHIVO INT NOT NULL,
    RUTA_ARCHIVO VARCHAR(300) NULL,
    FECHA DATE NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_ARCHIVO PRIMARY KEY (ID_ARCHIVO),
    CONSTRAINT ARCHIVO_TIPO_FK FOREIGN KEY (ID_TIPO_ARCHIVO)
        REFERENCES FIDE_TIPO_ARCHIVO_TB (ID_TIPO_ARCHIVO),
    CONSTRAINT ARCHIVO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_EXPEDIENTE_TB (
    ID_EXPEDIENTE INT NOT NULL,
    FECHA_DE_CREACION DATE NULL,
    ID_PROCEDIMIENTO INT NOT NULL,
    ID_NOTA INT NOT NULL,
    ID_ARCHIVO INT NOT NULL,
    ID_ALERTA INT NOT NULL,
    ID_CONSENTIMIENTO INT NOT NULL,
    ID_ODONTOGRAMA INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_EXPEDIENTE PRIMARY KEY (ID_EXPEDIENTE),
    CONSTRAINT EXPEDIENTE_PROCEDIMIENTO_FK FOREIGN KEY (ID_PROCEDIMIENTO)
        REFERENCES FIDE_PROCEDIMIENTO_TB (ID_PROCEDIMIENTO),
    CONSTRAINT EXPEDIENTE_NOTA_FK FOREIGN KEY (ID_NOTA)
        REFERENCES FIDE_NOTA_CLINICA_TB (ID_NOTA),
    CONSTRAINT EXPEDIENTE_ARCHIVO_FK FOREIGN KEY (ID_ARCHIVO)
        REFERENCES FIDE_ARCHIVO_TB (ID_ARCHIVO),
    CONSTRAINT EXPEDIENTE_ALERTA_FK FOREIGN KEY (ID_ALERTA)
        REFERENCES FIDE_ALERTA_MEDICA_TB (ID_ALERTA),
    CONSTRAINT EXPEDIENTE_CONSENT_FK FOREIGN KEY (ID_CONSENTIMIENTO)
        REFERENCES FIDE_CONSENTIMIENTO_TB (ID_CONSENTIMIENTO),
    CONSTRAINT EXPEDIENTE_ODONTO_FK FOREIGN KEY (ID_ODONTOGRAMA)
        REFERENCES FIDE_ODONTOGRAMA_TB (ID_ODONTOLOGIA),
    CONSTRAINT EXPEDIENTE_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_USUARIO_EXPEDIENTE_TB (
    ID_USUARIO INT NOT NULL,
    ID_EXPEDIENTE INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_EXPEDIENTE),
    CONSTRAINT USR_EXP_USUARIO_FK FOREIGN KEY (ID_USUARIO)
        REFERENCES FIDE_USUARIO_TB (ID_USUARIO),
    CONSTRAINT USR_EXP_EXPEDIENTE_FK FOREIGN KEY (ID_EXPEDIENTE)
        REFERENCES FIDE_EXPEDIENTE_TB (ID_EXPEDIENTE)
);

CREATE TABLE FIDE_CATEGORIA_PRODUCTO_TB (
    ID_CATEGORIA INT NOT NULL,
    NOMBRE_CATEGORIA VARCHAR(100) NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_CATEGORIA_PRODUCTO PRIMARY KEY (ID_CATEGORIA),
    CONSTRAINT CATEGORIA_PRODUCTO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_PROVEEDOR_TB (
    ID_PROVEEDOR INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMER_APELLIDO VARCHAR(100) NULL,
    SEGUNDO_APELLIDO VARCHAR(100) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_PROVEEDOR PRIMARY KEY (ID_PROVEEDOR),
    CONSTRAINT PROVEEDOR_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_CORREO_PROVEEDOR_TB (
    ID_PROVEEDOR INT NOT NULL,
    CORREO VARCHAR(150) NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT CORREO_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR)
        REFERENCES FIDE_PROVEEDOR_TB (ID_PROVEEDOR),
    CONSTRAINT CORREO_PROVEEDOR_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_TELEFONO_PROVEEDOR_TB (
    ID_PROVEEDOR INT NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT TELEFONO_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR)
        REFERENCES FIDE_PROVEEDOR_TB (ID_PROVEEDOR),
    CONSTRAINT TELEFONO_PROVEEDOR_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_PRODUCTO_TB (
    ID_PRODUCTO INT NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(150) NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    STOCK_ACTUAL INT NULL,
    STOCK_MINIMO INT NULL,
    FECHA_VENCIMIENTO DATE NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA)
        REFERENCES FIDE_CATEGORIA_PRODUCTO_TB (ID_CATEGORIA),
    CONSTRAINT PRODUCTO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_PROVEEDOR_PRODUCTO_TB (
    ID_PROVEEDOR INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    PRIMARY KEY (ID_PROVEEDOR, ID_PRODUCTO),
    CONSTRAINT PROV_PROD_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR)
        REFERENCES FIDE_PROVEEDOR_TB (ID_PROVEEDOR),
    CONSTRAINT PROV_PROD_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO)
        REFERENCES FIDE_PRODUCTO_TB (ID_PRODUCTO)
);

CREATE TABLE FIDE_USO_PRODUCTO_TB (
    ID_USO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    ID_PROCEDIMIENTO INT NOT NULL,
    CANTIDAD INT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_USO_PRODUCTO PRIMARY KEY (ID_USO),
    CONSTRAINT USO_PRODUCTO_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO)
        REFERENCES FIDE_PRODUCTO_TB (ID_PRODUCTO),
    CONSTRAINT USO_PRODUCTO_PROC_FK FOREIGN KEY (ID_PROCEDIMIENTO)
        REFERENCES FIDE_PROCEDIMIENTO_TB (ID_PROCEDIMIENTO),
    CONSTRAINT USO_PRODUCTO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

CREATE TABLE FIDE_CONTABILIDAD_CITA_TB (
    ID_CONTABILIDAD INT NOT NULL,
    ID_CITA INT NOT NULL,
    PRIMARY KEY (ID_CONTABILIDAD, ID_CITA),
    CONSTRAINT CONT_CITA_CONTABILIDAD_FK FOREIGN KEY (ID_CONTABILIDAD)
        REFERENCES FIDE_CONTABILIDAD_TB (ID_CONTABILIDAD),
    CONSTRAINT CONT_CITA_CITA_FK FOREIGN KEY (ID_CITA)
        REFERENCES FIDE_CITAS_TB (ID_CITA)
);

CREATE TABLE FIDE_CONTABILIDAD_PACIENTE_TB (
    ID_USUARIO INT NOT NULL,
    ID_CONTABILIDAD INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_CONTABILIDAD),
    CONSTRAINT CONT_PAC_USUARIO_FK FOREIGN KEY (ID_USUARIO)
        REFERENCES FIDE_USUARIO_TB (ID_USUARIO),
    CONSTRAINT CONT_PAC_CONTABILIDAD_FK FOREIGN KEY (ID_CONTABILIDAD)
        REFERENCES FIDE_CONTABILIDAD_TB (ID_CONTABILIDAD)
);

-- Agregar columna de hora a la tabla de citas
ALTER TABLE FIDE_CITAS_TB
ADD HORA TIME NULL;

-- Agregar columna de doctor (ID_USUARIO del doctor asignado)
ALTER TABLE FIDE_CITAS_TB
ADD ID_DOCTOR INT NULL;

ALTER TABLE FIDE_CITAS_TB
ADD CONSTRAINT CITAS_DOCTOR_FK FOREIGN KEY (ID_DOCTOR)
    REFERENCES FIDE_USUARIO_TB (ID_USUARIO);

	INSERT INTO FIDE_MOTIVO_CITA_TB (ID_MOTIVO, DESCRIPCION, ID_ESTADO) VALUES
(2, 'Consulta general', 1),
(3, 'Limpieza dental', 1),
(4, 'Extracción', 1),
(5, 'Ortodoncia', 1),
(6, 'Endodoncia', 1),
(7, 'Revisión', 1);

INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, NOMBRE_ESTADO) VALUES
(3, 'Cancelada'),
(4, 'Rechazada'),
(5, 'Pendiente'),
(6, 'Confirmada')

INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, NOMBRE_ESTADO) VALUES
(7, 'Ausente'),
(8, 'Asistida'),
(9, 'Finalizada')

-- Métodos de pago
INSERT INTO FIDE_METODO_PAGO_TB (ID_METODO_PAGO, DESCRIPCION, ID_ESTADO) VALUES
(1, 'Efectivo', 1),
(2, 'Tarjeta', 1),
(3, 'SINPE', 1)

-- Gasto placeholder para contabilidad
INSERT INTO FIDE_GASTO_TB (ID_GASTO, DESCRIPCION, MONTO, FECHA, ID_ESTADO) VALUES
(1, 'Gasto general clínica', 0.00, GETDATE(), 1)

ALTER TABLE FIDE_TRATAMIENTO_TB
ADD MONTO DECIMAL(10,2) NULL;

ALTER TABLE FIDE_TRATAMIENTO_TB
ADD ID_CITA INT NULL;

ALTER TABLE FIDE_TRATAMIENTO_TB
ADD CONSTRAINT TRATAMIENTO_CITA_FK FOREIGN KEY (ID_CITA)
    REFERENCES FIDE_CITAS_TB (ID_CITA);

-- Catálogo de tipos de tratamiento con costo base
CREATE TABLE FIDE_CATALOGO_TRATAMIENTO_TB (
    ID_CATALOGO    INT          NOT NULL,
    NOMBRE         VARCHAR(150) NOT NULL,
    CATEGORIA      VARCHAR(50)  NULL,
    DURACION_MIN   INT          NULL,
    COSTO          DECIMAL(10,2) NOT NULL,
    COSTO_ANTERIOR DECIMAL(10,2) NULL,
    ID_ESTADO      INT          NOT NULL,
    FECHA_ACTUALIZACION DATE    NULL,
    CONSTRAINT PK_CATALOGO_TRATAMIENTO PRIMARY KEY (ID_CATALOGO),
    CONSTRAINT CATALOGO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);

-- Datos base del catálogo
INSERT INTO FIDE_CATALOGO_TRATAMIENTO_TB VALUES
(1,  'Limpieza dental',          'Preventivo',  45,  35000,  30000, 1, GETDATE()),
(2,  'Blanqueamiento',           'Estético',    60,  45000,  42000, 1, GETDATE()),
(3,  'Radiografía periapical',   'Preventivo',  15,  12000,  10000, 1, GETDATE()),
(4,  'Extracción dental simple', 'Cirugía',     30,  25000,  25000, 1, GETDATE()),
(5,  'Ortodoncia (mensualidad)', 'Ortodoncia',  30,  55000,  50000, 1, GETDATE()),
(6,  'Resina dental',            'Restaurador', 50,  30000,  28000, 1, GETDATE()),
(7,  'Endodoncia',               'Endodoncia',  90,  80000,  75000, 1, GETDATE()),
(8,  'Corona de porcelana',      'Restaurador', 120, 95000,  90000, 1, GETDATE()),
(9,  'Implante dental',          'Cirugía',     180, 350000, 320000,1, GETDATE()),
(10, 'Profilaxis infantil',      'Preventivo',  30,  18000,  15000, 1, GETDATE()),
(11, 'Blanqueamiento láser',     'Estético',    90,  75000,  70000, 1, GETDATE()),
(12, 'Puente dental (3 piezas)', 'Restaurador', 90,  120000, 110000,1, GETDATE()),
(13, 'Extracción muela juicio',  'Cirugía',     60,  40000,  38000, 1, GETDATE()),
(14, 'Sellante dental',          'Preventivo',  20,  8000,   8000,  1, GETDATE());